import Head from "next/head";
import WeatherApp from "../components/WeatherApp";
import Clock from "../components/Clock/Clock";


export default function Home() {
  return (
    <div className="bg-black w-full h-screen flex">
      <Head>
        <title>Weathep App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-auto w-full">
        <Clock />
      </div>
    </div>
  );
}
